name: deeplab
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - scipy
  - statsmodels
  - sympy
  - matplotlib
  - basemap
  - seaborn
  - dash
  - plotly
  - holoviews
  - geoviews
  - hvplot
  - panel
  - altair
  - vega_datasets
  - datashader
  - dask
  - pyspark
  - pandas
  - geopandas
  - pyarrow
  - fastparquet
  - openpyxl
  - xlrd
  - h5py
  - pytables
  - numba
  - scikit-learn
  - scikit-image
  - pillow
  - spacy
  - gensim
  - networkx
  - sqlalchemy
  - postgresql
  - psycopg2
  - sqlite
  - scrapy
  - beautifulsoup4
  - lxml
  - psutil
  - tqdm
  - pytest
  - tox
  - jupyterlab
  - ipython==7.5
  - ipykernel
  - ipywidgets
  - sphinx
  - nbsphinx
  - sphinx_rtd_theme
  - recommonmark
